name: Package Application with Pyinstaller

on:
  pull_request:
    branches: [ main ]

jobs:
  package_windows_executable:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Setup Python
        uses: actions/setup-python@v3
        with:
          python-version: '3.x'
          cache: 'pip'
          cache-dependency-path: |
            requirements-build.txt
      - name: Install dependencies
        run: |
          python -m pip install -r requirements-build.txt --upgrade pip
      - name: Create build.spec
        run: | 
          pyinstaller src/crc_calculator/__main__.py
          mv __main__.spec build.spec
      - name: Package windows application
        uses: JackMcKew/pyinstaller-action-windows@main
        with:
          path: .
          spec: build.spec
          requirements: requirements-build.txt
      - name: Upload artifact
        uses: actions/upload-artifact@v3
        with:
          path: dist/windows
