name: Python Test CI
on:
  pull_request:

jobs:
  ci:
    name: Run test ci on python ${{ matrix.py }}
    runs-on: ubuntu-latest
    strategy:
      matrix:
        py:
          - "3.7"
          - "3.8"
          - "3.9"
          - "3.10"
    steps:
    - name: Checkout repository
      uses: actions/checkout@v2
    - name: Setup python ${{ matrix.py }}
      uses: actions/setup-python@v2
      with:
        python-version: ${{ matrix.py }}
        cache: 'pip'
        cache-dependency-path: |
          requirements-dev.txt
    - name: Install dependencies
      run: python -m pip install --upgrade pip tox
    - name: Run tests
      run: tox
