name: Release Drafter

on:
  push:
    tags:
      - 'v*'

jobs:
  update_release_draft:
    runs-on: ubuntu-latest
    outputs:
      upload_url: ${{ steps.release_drafter.outputs.upload_url }}
    steps:
      - name: Release Drafter
        id: release_drafter
        uses: release-drafter/release-drafter@v5
        with:
          config-name: release-drafter-config.yml
          name: ${{ github.ref_name }}
          tag: ${{ github.ref_name }}
        env:
          GITHUB_TOKEN: ${{ secrets.PERSONAL_ACCESS_TOKEN }}

  package_windows_executable:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Setup Python
        uses: actions/setup-python@v3
        with:
          python-version: 3.10
          cache: 'pip'
          cache-dependency-path: |
            requirements-build.txt
      - name: Install dependencies
        run: |
          python -m pip install -r requirements-build.txt --upgrade pip
      - name: Create spec file for packaging
        run: |
          pyinstaller src/crc_calculator/__main__.py
      - name: Package windows application
        uses: JackMcKew/pyinstaller-action-windows@main
        with:
          path: .
          spec: __main__.spec
          requirements: requirements-build.txt
      - name: Upload Release Asset
        id: upload-release-asset
        uses: actions/upload-release-asset@v1.0.1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          upload_url: ${{ needs.update_release_draft.outputs.upload_url }}
          asset_path: dist/windows
          asset_name: crc-calculator-${{ github.ref_name }}-windows
          asset_content_type: application/zip
